name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - run: bundle install
      - run: bundle exec fastlane tests
